// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/donations/history": {
    params: {};
  };
  "/donor/home": {
    params: {};
  };
  "/donor/match/:matchId": {
    params: {
      "matchId": string;
    };
  };
  "/donor/match/:matchId/checkin": {
    params: {
      "matchId": string;
    };
  };
  "/errors/async-effect-error": {
    params: {};
  };
  "/errors/event-handler-error": {
    params: {};
  };
  "/errors/hook-rule": {
    params: {};
  };
  "/errors/infinite-render-loop": {
    params: {};
  };
  "/errors/json-parse-error": {
    params: {};
  };
  "/errors/missing-component": {
    params: {};
  };
  "/errors/null-access": {
    params: {};
  };
  "/errors/render-object": {
    params: {};
  };
  "/errors/type-error-not-function": {
    params: {};
  };
  "/errors/undefined-access": {
    params: {};
  };
  "/errors/unhandled-promise": {
    params: {};
  };
  "/hospital/dashboard": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/matches/:matchId/chat": {
    params: {
      "matchId": string;
    };
  };
  "/matches/:matchId/tracking": {
    params: {
      "matchId": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/register/confirmation": {
    params: {};
  };
  "/requests/history": {
    params: {};
  };
  "/requests/:requestId": {
    params: {
      "requestId": string;
    };
  };
  "/__create/social-dev-shim": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/donations/history" | "/donor/home" | "/donor/match/:matchId" | "/donor/match/:matchId/checkin" | "/errors/async-effect-error" | "/errors/event-handler-error" | "/errors/hook-rule" | "/errors/infinite-render-loop" | "/errors/json-parse-error" | "/errors/missing-component" | "/errors/null-access" | "/errors/render-object" | "/errors/type-error-not-function" | "/errors/undefined-access" | "/errors/unhandled-promise" | "/hospital/dashboard" | "/login" | "/matches/:matchId/chat" | "/matches/:matchId/tracking" | "/profile" | "/register" | "/register/confirmation" | "/requests/history" | "/requests/:requestId" | "/__create/social-dev-shim" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./donations/history/page.jsx": {
    id: "donations/history/page";
    page: "/donations/history";
  };
  "./donor/home/page.jsx": {
    id: "donor/home/page";
    page: "/donor/home";
  };
  "./donor/match/[matchId]/page.jsx": {
    id: "donor/match/[matchId]/page";
    page: "/donor/match/:matchId";
  };
  "./donor/match/[matchId]/checkin/page.jsx": {
    id: "donor/match/[matchId]/checkin/page";
    page: "/donor/match/:matchId/checkin";
  };
  "./errors/async-effect-error/page.jsx": {
    id: "errors/async-effect-error/page";
    page: "/errors/async-effect-error";
  };
  "./errors/event-handler-error/page.jsx": {
    id: "errors/event-handler-error/page";
    page: "/errors/event-handler-error";
  };
  "./errors/hook-rule/page.jsx": {
    id: "errors/hook-rule/page";
    page: "/errors/hook-rule";
  };
  "./errors/infinite-render-loop/page.jsx": {
    id: "errors/infinite-render-loop/page";
    page: "/errors/infinite-render-loop";
  };
  "./errors/json-parse-error/page.jsx": {
    id: "errors/json-parse-error/page";
    page: "/errors/json-parse-error";
  };
  "./errors/missing-component/page.jsx": {
    id: "errors/missing-component/page";
    page: "/errors/missing-component";
  };
  "./errors/null-access/page.jsx": {
    id: "errors/null-access/page";
    page: "/errors/null-access";
  };
  "./errors/render-object/page.jsx": {
    id: "errors/render-object/page";
    page: "/errors/render-object";
  };
  "./errors/type-error-not-function/page.jsx": {
    id: "errors/type-error-not-function/page";
    page: "/errors/type-error-not-function";
  };
  "./errors/undefined-access/page.jsx": {
    id: "errors/undefined-access/page";
    page: "/errors/undefined-access";
  };
  "./errors/unhandled-promise/page.jsx": {
    id: "errors/unhandled-promise/page";
    page: "/errors/unhandled-promise";
  };
  "./hospital/dashboard/page.jsx": {
    id: "hospital/dashboard/page";
    page: "/hospital/dashboard";
  };
  "./login/page.jsx": {
    id: "login/page";
    page: "/login";
  };
  "./matches/[matchId]/chat/page.jsx": {
    id: "matches/[matchId]/chat/page";
    page: "/matches/:matchId/chat";
  };
  "./matches/[matchId]/tracking/page.jsx": {
    id: "matches/[matchId]/tracking/page";
    page: "/matches/:matchId/tracking";
  };
  "./profile/page.jsx": {
    id: "profile/page";
    page: "/profile";
  };
  "./register/page.jsx": {
    id: "register/page";
    page: "/register";
  };
  "./register/confirmation/page.jsx": {
    id: "register/confirmation/page";
    page: "/register/confirmation";
  };
  "./requests/history/page.jsx": {
    id: "requests/history/page";
    page: "/requests/history";
  };
  "./requests/[requestId]/page.jsx": {
    id: "requests/[requestId]/page";
    page: "/requests/:requestId";
  };
  "./__create/social-dev-shim/page.jsx": {
    id: "__create/social-dev-shim/page";
    page: "/__create/social-dev-shim";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "donations/history/page": typeof import("./src/app/./donations/history/page.jsx");
  "donor/home/page": typeof import("./src/app/./donor/home/page.jsx");
  "donor/match/[matchId]/page": typeof import("./src/app/./donor/match/[matchId]/page.jsx");
  "donor/match/[matchId]/checkin/page": typeof import("./src/app/./donor/match/[matchId]/checkin/page.jsx");
  "errors/async-effect-error/page": typeof import("./src/app/./errors/async-effect-error/page.jsx");
  "errors/event-handler-error/page": typeof import("./src/app/./errors/event-handler-error/page.jsx");
  "errors/hook-rule/page": typeof import("./src/app/./errors/hook-rule/page.jsx");
  "errors/infinite-render-loop/page": typeof import("./src/app/./errors/infinite-render-loop/page.jsx");
  "errors/json-parse-error/page": typeof import("./src/app/./errors/json-parse-error/page.jsx");
  "errors/missing-component/page": typeof import("./src/app/./errors/missing-component/page.jsx");
  "errors/null-access/page": typeof import("./src/app/./errors/null-access/page.jsx");
  "errors/render-object/page": typeof import("./src/app/./errors/render-object/page.jsx");
  "errors/type-error-not-function/page": typeof import("./src/app/./errors/type-error-not-function/page.jsx");
  "errors/undefined-access/page": typeof import("./src/app/./errors/undefined-access/page.jsx");
  "errors/unhandled-promise/page": typeof import("./src/app/./errors/unhandled-promise/page.jsx");
  "hospital/dashboard/page": typeof import("./src/app/./hospital/dashboard/page.jsx");
  "login/page": typeof import("./src/app/./login/page.jsx");
  "matches/[matchId]/chat/page": typeof import("./src/app/./matches/[matchId]/chat/page.jsx");
  "matches/[matchId]/tracking/page": typeof import("./src/app/./matches/[matchId]/tracking/page.jsx");
  "profile/page": typeof import("./src/app/./profile/page.jsx");
  "register/page": typeof import("./src/app/./register/page.jsx");
  "register/confirmation/page": typeof import("./src/app/./register/confirmation/page.jsx");
  "requests/history/page": typeof import("./src/app/./requests/history/page.jsx");
  "requests/[requestId]/page": typeof import("./src/app/./requests/[requestId]/page.jsx");
  "__create/social-dev-shim/page": typeof import("./src/app/./__create/social-dev-shim/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};